name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "$DEPLOY_SSH_KEY"

    - name: Deploy to server
      env:
        HOST: ${{ secrets.DEV_HOST }}
        USER: ${{ secrets.DEV_USER }}
        TARGET: ${{ secrets.DEV_TARGETDIRECTORY }}
      run: |
        npm install
        npm run build
        echo "Compiled assets..."

        rm -rf node_modules
        rm package.json
        rm package-lock.json
        rm -rf .github/
        rm -rf .git/
        rm .gitignore
        rm README.md

        echo "Uploading files..." 
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete ./ $USER@$HOST:$TARGET