name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      run: |
        echo "$DEPLOY_SSH_KEY" > deploy_key
        chmod 600 deploy_key

    - name: Deploy to server
      env:
        HOST: ${{ secrets.DEV_HOST }}
        USER: ${{ secrets.DEV_USER }}
        TARGET: ${{ secrets.DEV_TARGETDIRECTORY }}
      run: |
        npm install

        echo "Compile assets"
        sass --watch scss/main.scss:assets/css/style.css
        terser js/App.js -o assets/js/App.min.js && javascript-obfuscator assets/js/App.min.js --output assets/js/App.js

        echo "Remove unneeded code..."
        rm -rf node_modules
        rm package.json
        rm -rf scss/
        rm -rf js/
        rm -rf .github/
        rm -rf .git/
        rm .gitignore
        rm README.md

        echo "Uploading files..."
        rsync -avz -e "ssh -i deploy_key -o StrictHostKeyChecking=no" --delete ./ $USER@$HOST:$TARGET